# Generated by Django 4.2.3 on 2023-07-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='text2',
            field=models.TextField(default=1, verbose_name='Text 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='age',
            field=models.CharField(default=1, max_length=10, verbose_name='Age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='height',
            field=models.CharField(default=1, max_length=20, verbose_name='Height'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='occupation',
            field=models.CharField(default=1, max_length=50, verbose_name='Occupation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='weight',
            field=models.CharField(default=1, max_length=20, verbose_name='Weight'),
            preserve_default=False,
        ),
    ]
