# Generated by Django 4.2.3 on 2023-07-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_services_text2_team_age_team_height_team_occupation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
