# Generated by Django 4.2.3 on 2023-07-14 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
                ('to_check', models.BooleanField(blank=True, verbose_name='Check Position')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
