# Generated by Django 4.2.3 on 2023-07-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='text1',
            field=models.TextField(default=1, verbose_name='Text 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='text2',
            field=models.TextField(default=1, verbose_name='Text 2'),
            preserve_default=False,
        ),
    ]
