# Generated by Django 4.2.3 on 2023-07-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_team_text1_team_text2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classespage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=50, verbose_name='Document Title')),
                ('background', models.ImageField(upload_to='images', verbose_name='Backgorund')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('path1', models.CharField(max_length=30, verbose_name='Path 1')),
                ('path2', models.CharField(max_length=30, verbose_name='Path 2')),
                ('path3', models.CharField(max_length=30, verbose_name='Path 3')),
                ('title2', models.CharField(max_length=50, verbose_name='Title 2')),
                ('info1', models.CharField(max_length=25, verbose_name='Info 1')),
                ('info2', models.CharField(max_length=25, verbose_name='Info 2')),
                ('info3', models.CharField(max_length=25, verbose_name='Info 3')),
                ('info4', models.CharField(max_length=25, verbose_name='Info 4')),
            ],
            options={
                'verbose_name': 'Classespage',
                'verbose_name_plural': 'Classespage',
            },
        ),
    ]
