from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(Header)
admin.site.register(FooterContent)
admin.site.register(Footer)
admin.site.register(Homepage)
admin.site.register(Title)
admin.site.register(Reason)
admin.site.register(Offer)
admin.site.register(Appointment)
admin.site.register(Pricing)
admin.site.register(HomeGallery)
admin.site.register(Aboutpage)
admin.site.register(About)
admin.site.register(AboutFill)
admin.site.register(Testimonial)
admin.site.register(Servicespage)
admin.site.register(Services)
admin.site.register(Teampage)
admin.site.register(Team)
admin.site.register(Contactpage)
admin.site.register(Contact)
admin.site.register(ContactPost)
admin.site.register(Calculatorpage)
admin.site.register(CalculatorBMI)
admin.site.register(BMI_STATUS)
admin.site.register(Gallerypage)
admin.site.register(Gallery)
admin.site.register(Classespage)